### ISSUE TITLE
TKBool.lib different in /lib and /libd

### ISSUE THREAD

**Issue by aiksiongkoh** [FreeCAD/FreeCAD-LibPack#24]
All the TKxxxxx.lib files in /libd are identical to those in /lib, except for TKBool.lib
Is that intentional?
Is /libd needed anymore?

Thanks,
Aik-Siong Koh

**Comment by chennes** [comment]
I believe this bug report is about LibPack 2.11 -- LibPack 3 no longer has a libd directory, as it does not currently support compiling debug versions of the OCCT libraries.
