### ISSUE TITLE
Suggestion: Please "port" this effort to conan

### ISSUE THREAD

**Issue by loopless** [FreeCAD/FreeCAD-LibPack#29]
It seems to me a lot of the useful work of this project is, to some extent, reproducing what could be done much more easily with conan.  This complex web of dependencies is exactly the problem conan solves, and in a very nice manner.  Leveraging conan would make life easier for everyone across all build platforms.

**Comment by chennes** [comment]
The aim of the LibPack is not so much package management as providing a single fixed, canonical download of all the dependencies in one go, which is convenient for some use cases. For dependency/package management we have a Conda setup that works well, and it's not clear to me what benefit adding another mechanism is. That said, if someone is interested in setting up conan (or chocolatey, or vcpkg, or nuget, or whatever...), go for it!

**Comment by loopless** [comment]
Got it, I see the motivation for what you are doing. I am not familiar with Conda as we are heavily committed to conan/artifactory
