### ISSUE TITLE
LibPack: making progress for FreeCAD 0.20

### ISSUE THREAD

**Issue by donovaly** [FreeCAD/FreeCAD-LibPack#3]
Hello @scottmudge and @apeltauer and @wwmayer , FreeCAD 0.20 is stalled because of a lacking LibPack. I put Scotts' and apeltauer's latest LibPack here to work on it jointly.

apeltauer's LibPack (https://github.com/FreeCAD/FreeCAD-LibPack/releases/tag/1.0) is what we used fro FreeCAD 0.19. What needs to be done is
https://github.com/FreeCAD/FreeCAD-LibPack/blob/master/Requirements.txt

Scott, can you contribute the OCC part? Apeltauer failed because Netgen does not compile for him. Realthunder told me that with your LibPack (https://github.com/FreeCAD/FreeCAD-LibPack/releases/tag/2.0) Netgen compiles but is actually not fully usable. So we need to check Netgen in every case.
I remember that Netgen is always tricky. For FC 0.19 we fixed a version of Netgen and @wwmayer had a look what needs to be changed in FC to make the NetgenPlugin compiling. Then we never touched Netgen for the whole FC 019 series. I would do for 0.20 the same. @wwmayer , what do you think?

Concerning Qt, I will have a look at the weekend.

**Comment by wwmayer** [comment]
> what do you think?

Which netgen version is used for the planned LibPack? As said in this [thread](https://github.com/trelau/SMESH/pull/28#issuecomment-751547384) the official Salome project uses netgen 5.3 and so does trelau in his fork. When I looked at netgen the last time there were no real technical improvements but only make things more complicated for the integration into smesh.

So, if netgen 5.3 still works then use this version.

Links:
https://github.com/trelau/SMESH/pull/28
https://github.com/trelau/SMESH/pull/31

**Comment by donovaly** [comment]
> Which netgen version is used for the planned LibPack? As said in this [thread](https://github.com/trelau/SMESH/pull/28#issuecomment-751547384) the official Salome project uses netgen 5.3 and so does trelau in his fork.
> 
> Links: [trelau/SMESH#28](https://github.com/trelau/SMESH/pull/28) [trelau/SMESH#31](https://github.com/trelau/SMESH/pull/31)

I have not much knowledge. The info I got from @apeltauer is that he cannot compile OCC 7.6 because of NetGen.

Here I see that Netgen 6.2 is supported: https://github.com/trelau/SMESH/commits/master

However, it is not clear to me how this is connected to OCC.

--------------

For info: I am trying hard since hours to compile Qt 5.15.3 but failed (lots of unresolved externals :-( when compiling QQml)

**Comment by wwmayer** [comment]
> The info I got from @apeltauer is that he cannot compile OCC 7.6 because of NetGen.

It's rather the other way round.

> Here I see that Netgen 6.2 is supported: https://github.com/trelau/SMESH/commits/master

Thanks for the pointer.

> However, it is not clear to me how this is connected to OCC.

smesh is the mesh library needed for FE simulations. As meshing algorithms it provides Mefisto as a fix part and optionally netgen. smesh and netgen both depend on occ.

The issue is that occ breaks existing API for almost every release which makes it difficult to keep applications/libraries up-to-date. The second issue is that netgen does the same and in the past there was not even a way to distinguish between different releases.

The result is that it's a nightmare to keep the netgenplugin working (that is part of smesh).

**Comment by donovaly** [comment]
OK. I compiled now OCC 7.6.2 successfully.
Since SMESH supports now NetGen 6.2.201, let's use this Netgen version. I installed it from here now:
https://github.com/NGSolve/ngsolve/releases/tag/v6.2.2101

Now I am stuck. What do I have to do now? Can I just copy its DLLs to the BIN folder of the LibPack, the upload the LibPack and you will have a look? Or do I have to compile e.g. SMESH before?

**Comment by donovaly** [comment]
> Can I just copy its DLLs to the BIN folder of the LibPack, the upload the LibPack and you will have a look?

stupid me, of course not, because we need the debug libraries as well :-(. I will have a look if I can compile.

**Comment by donovaly** [comment]
OK, here we are. This is a LibPack with OCC 7.6.2 and NetGen 6.2.2101:
https://github.com/FreeCAD/FreeCAD-LibPack/releases/tag/2.1

With this I get this error:
```

1>   Creating library D:/FreeCAD-build/lib/Release/SMESHDS.lib and object D:/FreeCAD-build/lib/Release/SMESHDS.exp
1>SMESHDS_Mesh.obj : error LNK2019: unresolved external symbol "public: static void __cdecl TopExp::MapShapes(class TopoDS_Shape const &,class NCollection_IndexedMap<class TopoDS_Shape,class TopTools_ShapeMapHasher> &)" (?MapShapes@TopExp@@SAXAEBVTopoDS_Shape@@AEAV?$NCollection_IndexedMap@VTopoDS_Shape@@VTopTools_ShapeMapHasher@@@@@Z) referenced in function "public: void __cdecl SMESHDS_Mesh::ShapeToMesh(class TopoDS_Shape const &)" (?ShapeToMesh@SMESHDS_Mesh@@QEAAXAEBVTopoDS_Shape@@@Z)
1>SMESHDS_Mesh.obj : error LNK2019: unresolved external symbol "public: void __cdecl TopExp_Explorer::Destroy(void)" (?Destroy@TopExp_Explorer@@QEAAXXZ) referenced in function "public: __cdecl TopExp_Explorer::~TopExp_Explorer(void)" (??1TopExp_Explorer@@QEAA@XZ)
1>D:\FreeCAD-build\bin\SMESHDS.dll : fatal error LNK1120: 2 unresolved externals
```

I think must update SMSH too for the LibPack but I don't understand how.

**Comment by luzpaz** [comment]
JFYI, there may be some useful info in https://github.com/trelau/SMESH/pull/64

**Comment by wwmayer** [comment]
> TopExp::MapShapes
> TopExp_Explorer::Destroy(void)

TopExp classes are provided with the TKBrep library. Do you have this one included in the CMakeLists.txt file of SMESH?

**Comment by donovaly** [comment]
> Do you have this one included in the CMakeLists.txt file of SMESH?

I don't understand. I took the existing LibPack and put in there the OCC I compiled. I did nothing else.

I need someone to explain me how the SMESH things work since I even did not the concept of SMESH -> I sent you a private message via the forum.

**Comment by donovaly** [comment]
Here is a new attempt for a LibPack: https://github.com/FreeCAD/FreeCAD-LibPack/releases/tag/2.2

As we agreed, Qt stays at 5.15.2 and we use FreeCAD's SMESH. Therefore I only updated OCC and Netgen and now the Netgen plugin has to be made compiling.

**Comment by luzpaz** [comment]
It sucks BUT it also makes sense that this would be a botleneck for release when we're right on the edge of the last Qt5 package before Qt6. Hopefully we can make a smoother transition to Qt6 in v0.21

**Comment by donovaly** [comment]
Update: Meanwhile I was able to compile OCC + the patches from @blobfish. I documented (and will further document) the build process here: 
https://wiki.freecadweb.org/Compile_on_Windows#Compiling_OpenCASCADE

@wwmayer could fix Netgen. I will document its build here: https://wiki.freecadweb.org/Compile_on_Windows#Compiling_Netgen

**Comment by donovaly** [comment]
We eventually have a working LibPack we an use for FC 0.20: https://github.com/FreeCAD/FreeCAD-LibPack/releases/tag/2.4

-> closing this issue as fixed.
