### ISSUE TITLE
Missing boost dir

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD-LibPack#34]
I tried 3.1 and got this error:```

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at C:/freecad_libs/LibPack/lib/cmake/Boost-1.86.0/BoostConfig.cmake:141 (find_package):
  Could not find a package configuration file provided by "boost_python"
  (requested version 1.86.0) with any of the following names:

    boost_pythonConfig.cmake
    boost_python-config.cmake

  Add the installation prefix of "boost_python" to CMAKE_PREFIX_PATH or set
  "boost_python_DIR" to a directory containing one of the above files.  If
  "boost_python" provides a separate development package or SDK, be sure it
  has been installed.		C:/freecad_libs/LibPack/lib/cmake/Boost-1.86.0/BoostConfig.cmake	141		

```

**Comment by chennes** [comment]
You need FreeCAD PR 18288 to use this version of the LibPack: we are going to remove Boost.Python.

**Comment by MisterMakerNL** [comment]
With that PR it worked!
