### ISSUE TITLE
LIbpack 3.1.0 shiboken6 build error

### ISSUE THREAD

**Issue by loopless** [FreeCAD/FreeCAD-LibPack#36]
Note: I disabled CMake "quiet mode" to get the messages

[INFO]: Qt Source dir:
[INFO]: Configuring module shiboken6 (d:\free_cad_build\FreeCAD-LibPack\working\pyside\sources\shiboken6)...
CMake Error at D:/free_cad_build/FreeCAD-LibPack/working/LibPack-1.1.0-v3.1.0-Release/lib/cmake/llvm/LLVMExports.cmake:1041 (message):
  The imported target "llvm-tblgen" references the file

     "D:/free_cad_build/FreeCAD-LibPack/working/LibPack-1.1.0-v3.1.0-Release/bin/llvm-tblgen.exe"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/free_cad_build/FreeCAD-LibPack/working/LibPack-1.1.0-v3.1.0-Release/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  D:/free_cad_build/FreeCAD-LibPack/working/LibPack-1.1.0-v3.1.0-Release/lib/cmake/llvm/LLVMConfig.cmake:258 (include)
  D:/free_cad_build/FreeCAD-LibPack/working/LibPack-1.1.0-v3.1.0-Release/lib/cmake/clang/ClangConfig.cmake:10 (find_package)
  cmake/ShibokenHelpers.cmake:170 (find_package)
  cmake/ShibokenSetup.cmake:37 (setup_clang)
  CMakeLists.txt:13 (include)

**Comment by chennes** [comment]
Related to the updated libclang, maybe? Is this actually causing a LibPack creation failure on your system?

**Comment by loopless** [comment]
Yes, the LibPack pyside6 build fails due to that issue. I "fixed" it by copying the file to the "bin" directory of LibPack.

Then I also hit this error 
https://stackoverflow.com/questions/78770245/shiboken6-constexpr-variable-must-be-initialized-by-a-constant-expression

This is a tricky one, as I could not find how to pass --clang-options=-D _CRT_USE_BUILTIN_OFFSETOF to the "generation" phase where shiboken6 is used to generate the QT6 interfaces.

**Comment by chennes** [comment]
Oh I see, I did not u sweat and that you were using clang to compile. Let me know what you figure out, and feel free to submit a PR with your fixes.

**Comment by loopless** [comment]
No, I am not using clang to compile. 
shiboken uses clang as its "compiler" when it is generating code. So any code passed to shiboken must be "clang" compatible.

Anyway, I deleted the pyside6 directory and started from scratch after doing the following

- Updating my Visual Studio 2022 to 17.12.3
- Made sure to NOT include the MS "clang" toolset in the VS install

And everything now passed.
