### ISSUE TITLE
two problems：fmt and  .pdb 

### ISSUE THREAD

**Issue by zhouji963** [FreeCAD/FreeCAD-LibPack#7]
1.When debugging, fmt has an error. After checking, it is found that the debug configuration file is missing under the  folder “LibPack-0.21-V2.10\lib\cmake\fmt”
2.Unable to perform Python/Native Debugging in VS，because   .pdb files are missing in the following location，：
 LibPack-0.21-V2.10\bin\
 LibPack-0.21-V2.10\DLLs\
 LibPack-0.21-V2.10\bin\Lib\vebv\scripts\nt

Could you improve  these two  problems ? Thank you!

My English is not good, please forgive me！

**Comment by tmksw** [comment]
I also observed an issue with libfmt in debug mode. In Visual Studio for debug configuration I got following error:
```
fmt.lib(format.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in cxx_extensions.obj
fmt.lib(format.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in cxx_extensions.obj
```
However release build works as expected.

**Comment by adrianinsaval** [comment]
is this still a problem in the latest libpack? @zhouji963

**Comment by chennes** [comment]
At present LibPack 3 only supports compiling in Release and RelWithDebInfo modes. We plan to add debug support in the future, pending getting a working debug build of numpy. I'm going to close this ticket since it related to LibPack 2, which is no longer supported.
